{
  "json": {
    "id": "唯一标识",
    "posName": "职位名称",
    "posClass": "职位类别",
    "posDesc": "职位描述",
    "posUpdateUser": "修改人"
  },
  "form": [{
    "type": "input",
    "id": "id",
    "label": "",
    "placeholder": "唯一标识"
  }, {
    "type": "input",
    "id": "posName",
    "label": "",
    "placeholder": "职位名称"
  }, {
    "type": "input",
    "id": "posClass",
    "label": "",
    "placeholder": "职位类别"
  }, {
    "type": "input",
    "id": "posDesc",
    "label": "",
    "placeholder": "职位描述"
  }, {
    "type": "input",
    "id": "posUpdateUser",
    "label": "",
    "placeholder": "修改人"
  }],
  "forms": [{
    "columnName": "id",
    "columnTitle": "唯一标识",
    "width": "",
    "isShow": true
  }, {
    "columnName": "posName",
    "columnTitle": "职位名称",
    "width": "",
    "isShow": true
  }, {
    "columnName": "posClass",
    "columnTitle": "职位类别",
    "width": "",
    "isShow": true
  }, {
    "columnName": "posDesc",
    "columnTitle": "职位描述",
    "width": "",
    "isShow": true
  }, {
    "columnName": "posUpdateUser",
    "columnTitle": "修改人",
    "width": "",
    "isShow": true
  }]
}